localStorage.setItem("redirect_url",window.location.href);
if(!openid){
	window.location.href="https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx795992462b631e70&redirect_uri=http%3A%2F%2Fshop.qietuan.org%2Foauth.php&response_type=code&scope=snsapi_userinfo&state=12345678901#wechat_redirect"
}
$('#cou').on('tap',function(){
	if(uid){
		$.post(config.oneCouponTake,{uid:uid,coupon_id:1591051744775975},function(datas){
			if(datas.error_code==0){
				showTips('领取成功~');
				setTimeout(function(){
					window.location.href = "http://shop.qietuan.org/product_details.html?itemID=1591050352267046&specId=0";
				},3000)
			}else{
				showTips(datas.error_msg);
			}
		})
	}else{
		window.localStorage.setItem('setIndexNum',1);
		window.location.href="register.html"
	}
})